---
- name: install
  ansible.builtin.apt:
    name: haproxy
    update_cache: yes

- name: configure
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy

- name: service
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes

- meta: flush_handlers
