---
- name: install
  ansible.builtin.unarchive:
    src: "{{ crictl_url }}"
    dest: /usr/local/bin
    remote_src: yes

- name: configure
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    mode: '0644'
