---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_instances:
      host01:
        type: master
        ip: 192.168.61.11
        instance_type: t3.medium
  roles:
    - aws-instances
