---
- name: install
  apt:
    name:
      - jq
      - tmux
      - unzip
      - ca-certificates
    state: latest
    update_cache: yes
  environment:
    http_proxy: "http://192.168.61.1:7890"
    https_proxy: "http://192.168.61.1:7890"
