# -*- mode: ruby -*-
# vi: set ft=ruby :
cluster = {
  "host01" => { :ip => "192.168.61.11", :cpus => 2, :mem => 2048 }
}
groups = {
  "remote" => ["host01"],
  "vagrant" => ["host01"]
}

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://192.168.61.1:10809/"
    config.proxy.https    = "http://192.168.61.1:10809/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=777"]
  cluster.each do |name, data|
    config.vm.define name do |host|
      host.vm.hostname = name
      host.vm.network "forwarded_port", guest: 80, host: 48080
      host.vm.network "private_network", ip: "#{data[:ip]}"
      host.vm.provider :virtualbox do |vb, override|
        vb.cpus = data[:cpus]
        vb.memory = data[:mem]
      end
    end
  end
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbook.yaml"
  #   ansible.groups = groups
  # end
  config.vm.define 'controller' do |machine|
    machine.vm.network "private_network", ip: "192.168.61.61"

    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "playbook.yaml"
      ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all"
      ansible.inventory_path = "inventory"
    end
  end
end
