---
- name: security group
  amazon.aws.ec2_group:
    name: ansible_k8s
    state: absent
    region: "{{ aws_region }}"

- name: vpc info
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": ansible_k8s
  register: aws_vpc_output

- name: public route
  community.aws.ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc_output['vpcs'][0]['id'] }}"
    region: "{{ aws_region }}"
    lookup: tag
    tags:
      Name: Public
    state: absent
  when: aws_vpc_output['vpcs']

- name: internet gateway
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ aws_vpc_output['vpcs'][0]['id'] }}"
    region: "{{ aws_region }}"
    state: absent
  when: aws_vpc_output['vpcs']

- name: subnet
  amazon.aws.ec2_vpc_subnet:
    region: "{{ aws_region }}"
    az: "{{ aws_subnet_az }}"
    vpc_id: "{{ aws_vpc_output['vpcs'][0]['id'] }}"
    cidr: "{{ aws_private_cidr }}"
    state: absent
  when: aws_vpc_output['vpcs']

- name: vpc
  amazon.aws.ec2_vpc_net:
    name: ansible_k8s
    state: absent
    region: "{{ aws_region }}"
    cidr_block: "{{ aws_private_cidr }}"

- name: aws key
  amazon.aws.ec2_key:
    name: "{{ aws_key }}"
    state: absent

- name: ssh key directory
  ansible.builtin.file:
    path: "{{ role_path }}/../../../sshkeys"
    state: absent

