---
- hosts: localhost
  connection: local
  vars:
    aws_k8s_ssh_dir: "../../sshkeys"
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_lb:
      ip: 192.168.61.10
      ports:
      - name: ingress
        source: 80
        target: 80
      - name: api
        source: 6443
        target: 6443
    aws_instances:
      host01:
        type: master
        ip: 192.168.61.11
        instance_type: t3.medium
      host02:
        type: master
        ip: 192.168.61.12
        instance_type: t3.medium
      host03:
        type: master
        ip: 192.168.61.13
        instance_type: t3.medium
      host04:
        type: node
        ip: 192.168.61.14
        instance_type: t3.small
  roles:
    - aws-instances
